### ISSUE TITLE
Error with the number of items

### ISSUE THREAD

**Issue by mazulo** [pmbarrett314/curses-menu#13]
Hi, first of all thank you for your project. That's what I was looking for a few days!

So I'm building a tool in Python that collect news and show me in the terminal. I get the list of ID news and based on the number of news the user wants, I'll get each of it and add in menu. Something like this:

````python
for new in list_stories[:number_of_stories]:
        story = get_story(URL_ITEM.format(new))
        a += 1
        print(a)
        menu.append_item(FunctionItem(story['title'], int))
    menu.show()
````

Each `story` is a dict. Everything goes well until it runs `menu.show()`, that raises an exception when the number of items is greater than 40.

````bash
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mazulo/.virtualenvs/pynews/lib/python3.4/site-packages/cursesmenu/curses_menu.py", line 127, in _wrap_start
    curses.wrapper(self._main_loop)
  File "/usr/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/mazulo/.virtualenvs/pynews/lib/python3.4/site-packages/cursesmenu/curses_menu.py", line 180, in _main_loop
    self.draw()
  File "/home/mazulo/.virtualenvs/pynews/lib/python3.4/site-packages/cursesmenu/curses_menu.py", line 201, in draw
    self.screen.addstr(5 + index, 4, item.show(index), text_style)
_curses.error: addwstr() returned ERR
````

**Comment by mazulo** [comment]
So I was testing with some different options and got this:

When the number of items is greater than 7, I got this another error:

````bash
Exception in thread Thread-1:                                                                                                                                             
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mazulo/.virtualenvs/pynews/lib/python3.4/site-packages/cursesmenu/curses_menu.py", line 127, in _wrap_start
    curses.wrapper(self._main_loop)
  File "/usr/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/mazulo/.virtualenvs/pynews/lib/python3.4/site-packages/cursesmenu/curses_menu.py", line 184, in _main_loop
    self.process_user_input()
  File "/home/mazulo/.virtualenvs/pynews/lib/python3.4/site-packages/cursesmenu/curses_menu.py", line 261, in process_user_input
    if ord('1') <= user_input <= ord(str(len(self.items) + 1)):
TypeError: ord() expected a character, but string of length 2 found
````

**Comment by mazulo** [comment]
I think I find out a workaround to this problem. I create a new class that inherit from `CursesMenu` and override the `process_user_input` method, removing [this line](https://github.com/pmbarrett314/curses-menu/blob/master/cursesmenu/curses_menu.py#L261). Apparently everything works well.

````python
class NewCursesMenu(CursesMenu):

    def process_user_input(self):
        user_input = self.get_input()

        if user_input == curses.KEY_DOWN:
            self.go_down()
        elif user_input == curses.KEY_UP:
            self.go_up()
        elif user_input == ord("\n"):
            self.select()
````

**Comment by pmbarrett314** [comment]
I believe you have two separate issues. The first problem is covered in #2. I haven't worked through the best way to figure out if input will fit on a terminal and solve that issue.

I will push a fix for your second problem soon.

**Comment by mazulo** [comment]
Yeah, you're right. I solved the second problem with the `NewCursesMenu`, but if I have more than 32 (the maximum of items that fits in my terminal) the first error occurs.

I don't know yet what is the best way to do this, but I think that a good way would be something like that

![errorTerminal](http://wstaw.org/m/2016/02/15/plasma-desktopJz2197.png)

It's the [hn-cli](https://github.com/rafaelrinaldi/hn-cli), and it uses the [blessed](https://www.npmjs.com/package/blessed) npm package to create its UI in the terminal. If you look at the bottom right corner will see the percentage until the last item of the retrieved list.

Do you think that would be hard implement something like this in Python?
